const express = require('express')
const UserController = require('./controller/UserController')
const FormPreferenceController = require('./controller/FormPreferenceController')
const PerfilController = require('./controller/PerfilController')
const ItemController = require('./controller/ItemsController')
const LikeController = require('./controller/LikeController')
const DislikeController = require('./controller/DislikeController')
const RegisterController = require('./controller/RegisterController')
const ConfigController = require('./controller/ConfigController')
const routes = express.Router()

routes.get('/user', UserController.index)
routes.post('/user', UserController.store)
routes.post('/register', RegisterController.store)
routes.get('/form/preference', FormPreferenceController.index)
routes.get('/form/perfil', PerfilController.index)
routes.post('/form/perfil', PerfilController.store)
routes.get('/items', ItemController.index)
routes.post('/user/:itemId/likes', LikeController.store)
routes.get('/user/likes', LikeController.index)
routes.get('/user/my/items', ItemController.indexByUser)
routes.post('/user/:itemId/dislikes', DislikeController.store)
routes.get('/config', ConfigController.index)

module.exports = routes